### PR TITLE
Refactor pull-all.sh Script

### PR DESCRIPTION
**Pull request by Androbin**
Refactored to eliminate much of boilerplate code. The logic remains the same.

### CODE REVIEW

**Comment by Androbin** [comment]
@markusgeiss Friendly ping.

**Comment by Androbin** [comment]
@DanCarl857 Friendly ping.

**Comment by markusgeiss** [comment]
will give it a test run tomorrow ... then proceed merging it

**Comment by mgeiss** [comment]
Thanks (;

**Pull request merged**
